### ISSUE TITLE
adds a lot of unnecessary quotes in the csv file

### ISSUE THREAD

**Issue by MounikaKommineni** [adaltas/node-csv-stringify#95] opened 2019-07-25 06:34 UTC
Data in my csv file
```
_id,status,code,name
"""5d2c89fcdf9415eead6cc13f""",0,IN,"[{""lang_code"":""en"",""name"":""Hindusthan""}]"
```

**Comment by wdavidw** [comment] 2019-07-25 09:30
Please describe your issue in detail with an example supporting it.

**Comment by kiprobinson** [comment] 2019-11-20 18:26
_id is an object, so the system is using JSON.stringify, which converts it to `"5d2c89fcdf9415eead6cc13f"`. That would just show up in Excel/whatever as `5d2c89fcdf9415eead6cc13f`, not `"5d2c89fcdf9415eead6cc13f"`, so the field is quoted, which required doubling the quote characters for everything in that field.

You need to convert your mongo IDs to strings. I fixed this with:

```
            cast: {
                object: (object:any) => {
                    if(isObjectId(object))
                        return object.toString();
                    else
                        return JSON.stringify(object);
                },
            }
```

**Comment by wdavidw** [comment] 2019-11-20 23:40
Hope that help, closing because the issue is a bit old, but feel free to re-open if needed

**Closed by wdavidw** 2019-11-20 23:40 UTC
